routes/web.php
<?php

use App\Facades\Osmicard;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NexmoSMSController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('auth', 'verified');

Auth::routes(['verify' => true]);

Route::middleware('auth')->group(function () {
    Route::group(['prefix' => 'admin'], function () {

        Voyager::routes();

        Route::group(['middleware' => ['admin.user']], function () {

            Route::group(['prefix' => 'users', 'as' => 'admin.users.'], function () {
                Route::post('store_ajax',    ['as' => 'store_ajax',  'uses' => 'UserController@storeAjax']);
//            Route::delete('delete_car/{id}',    ['as' => 'delete_car',  'uses' => 'UserController@delete_car']);
                Route::post('select2',     ['as' => 'select2',        'uses' => 'UserController@select2']);
            });

            Route::group(['prefix' => 'agents', 'as' => 'admin.agents.'], function () {
                Route::post('approve_ajax',    ['as' => 'approve_ajax',  'uses' => 'AgentController@approveAjax']);
            });

            Route::group(['prefix' => 'dropzone', 'as' => 'admin.dropzone.'], function () {
                Route::get('/',        ['as' => 'index', 'uses' => 'PhotoController@index']);
                Route::post('store',   ['as' => 'store', 'uses' => 'PhotoController@store']);
            });

            Route::group(['prefix' => 'photos', 'as' => 'admin.photos.'], function () {
                Route::get('delete/{id}',        ['as' => 'delete', 'uses' => 'PhotoController@destroy']);
            });

            Route::group(['prefix' => 'orders', 'as' => 'admin.orders.'], function () {
                Route::post('photos',     ['as' => 'store_photos',  'uses' => 'OrderController@storePhotos']);
                Route::post('status',     ['as' => 'status',        'uses' => 'OrderController@updateStatus']);
            });

            Route::group(['prefix' => 'items', 'as' => 'admin.items.'], function () {
                Route::post('store',            ['as' => 'store',   'uses' => 'ItemController@store']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'ItemController@destroy']);
                Route::put('update_ajax',        ['as' => 'update_ajax',  'uses' => 'ItemController@updateAjax']);
//            Route::post('create_card',      ['as' => 'create_card',  'uses' => 'ItemController@createCard']);
            });

            Route::group(['prefix' => 'agent_orders', 'as' => 'admin.agent_orders.'], function () {
                Route::post('store',            ['as' => 'store',   'uses' => 'AgentOrderController@store']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'AgentOrderController@destroy']);
            });

            Route::group(['prefix' => 'card_templates', 'as' => 'admin.card_templates.'], function () {
                Route::get('fields',       ['as' => 'fields',   'uses' => 'CardTemplateController@fields']);
            });

            Route::group(['prefix' => 'cards', 'as' => 'admin.cards.'], function () {
                Route::post('store_ajax',       ['as' => 'store_ajax',   'uses' => 'CardController@storeAjax']);
                Route::post('update_event_ajax', ['as' => 'update_event_ajax',   'uses' => 'CardController@updateEventAjax']);
                Route::post('qrcode_ajax', ['as' => 'qrcode_ajax',   'uses' => 'CardController@getQRCodeAjax']);
                Route::post('send_sms_ajax', ['as' => 'send_sms_ajax',   'uses' => 'CardController@sendSMSAjax']);
            });

            Route::group(['prefix' => 'fields', 'as' => 'admin.fields.'], function () {
                Route::post('store_ajax',       ['as' => 'store_ajax',   'uses' => 'FieldController@storeAjax']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'FieldController@destroy']);
            });

            Route::group(['prefix' => 'services', 'as' => 'admin.services.'], function () {
                Route::get('services/list', ['as' => 'list', 'uses' => 'ServiceController@list']);
            });

            Route::group(['prefix' => 'verify', 'as' => 'admin.verify.'], function () {
                Route::post('send/{phone}', ['as' => 'send', 'uses' => 'VerifyController@send']);
                Route::post('check/{code}', ['as' => 'check', 'uses' => 'VerifyController@check']);
            });

            Route::get('sendSMS', [NexmoSMSController::class, 'index']);

            Route::group(['prefix' => 'report', 'as' => 'admin.report.'], function () {
                Route::get('/',    ['as' => 'index',  'uses' => 'ReportController@index']);
                Route::get('/search',    ['as' => 'search',  'uses' => 'ReportController@search']);
            });
        });

    });
});


// Agents
Route::middleware(['auth'])->group(function () {
    Route::group(['prefix' => 'agent', 'as' => 'agent.'], function () {
        Route::group(['prefix' => 'cards', 'as' => 'cards.'], function () {
            Route::get('/', ['as' => 'index', 'uses' => 'AgentCardController@index']);
            Route::get('show', ['as' => 'show', 'uses' => 'AgentCardController@show']);
            Route::post('store_ajax', ['as' => 'store_ajax',   'uses' => 'AgentCardController@storeAjax']);
            Route::post('update_event_ajax', ['as' => 'update_event_ajax',   'uses' => 'AgentCardController@updateEventAjax']);
            Route::post('get_card_ajax', ['as' => 'get_card_ajax',   'uses' => 'AgentCardController@getCardAjax']);
            Route::post('send_sms_ajax', ['as' => 'send_sms_ajax',   'uses' => 'AgentCardController@sendSMSAjax']);
            Route::post('qrcode_ajax', ['as' => 'qrcode_ajax',   'uses' => 'AgentCardController@getQRCodeAjax']);
        });
        Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
            Route::post('store', ['as' => 'store',   'uses' => 'AgentOrderController@store']);
        });
        Route::get('dashboard', ['as' => 'dashboard',  'uses' => 'AgentDashboardController@index']);
    });
});

// Voyager
//Route::group(['as' => 'voyager.'], function () {
//    event(new TCG\Voyager\Events\Routing());
//
//    Route::get('login', ['uses' => 'Voyager\VoyagerAuthController@login', 'as' => 'login']);
//
//    event(new TCG\Voyager\Events\RoutingAfter());
//});

// Some test
//Route::get('phpinfo', function () {
//    phpinfo();
//});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = [
        'qty', 'notice', 'price', 'service_id', 'order_id'
    ];

    public function order()
    {
        return $this->belongsTo('App\Order');
    }

    public function service()
    {
        return $this->belongsTo('App\Service');
    }

    public function card()
    {
        return $this->hasOne('App\Card');
    }

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreItemReuest;
use App\Http\Requests\UpdateItemRequest;
use App\Item;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreItemReuest $request)
    {
        $data = $request->validated();

        Item::create([
            'qty' => $data['qty'],
            'notice' => $data['notice'],
            'price' => $data['price'] ?? null,
            'order_id' => $data['order_id'],
            'service_id' => $data['service_id'],
        ]);

        return redirect()->back()->with([
            'message'    => __('voyager::generic.successfully_created'),
            'alert-type' => 'success',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::findOrFail($id);
        $deleted_success = $item->delete();

        if ($deleted_success) {
            return back()->with([
                'message'    => __('voyager::generic.successfully_deleted'),
                'alert-type' => 'success',
            ]);
        } else {
            return back()->with([
                'message'    => __('voyager::generic.error_deleting'),
                'alert-type' => 'error',
            ]);
        }
    }

    /**
     * Update the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateAjax(UpdateItemRequest $request)
    {
        $data = $request->validated();

        $item = Item::findOrFail($data['item_id']);
        $item_updated = $item->update($data);

        if (!$item_updated) {
            return redirect()->back()->with([
                'message'    => __('voyager::generic.update_failed'),
                'alert-type' => 'error',
            ]);
        } else {
            return redirect()->back()->with([
                'message'    => __('voyager::generic.successfully_updated'),
                'alert-type' => 'success',
            ]);
        }
    }
}

resources/views/admin/items/form-add.blade.php
<h4 class="title-form-h4">{{__('generic.add_service_to_this_order')}}</h4>
<form role="form"
      class="form-edit-add"
      action="{{route('admin.items.store')}}"
      method="POST">

    {{ csrf_field() }}

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="form-group col-md-7">
        <label class="control-label" for="service_id">{{ __('generic.service') }}</label>
        <select class="form-control select2-ajax-item"
                name="service_id"
                data-get-items-route="{{route('admin.services.list')}}">
            <option value="">{{__('voyager::generic.none')}}</option>
            @inject('service_model', 'App\Service')
            @php $services = $service_model->all() @endphp
            @foreach($services as $service)
                <option value="{{ $service->id }}" {{old('service_id') === $service->id ? 'selected' : ''}}>
                    {{ $service->name }}  ({{ $service->price }} ₸)
                </option>
            @endforeach
        </select>
    </div>
    <div class="form-group col-md-3">
        <label class="control-label" for="price">{{ __('generic.price') }} (₸)</label>
        <input type="number" name="price" value="{{old('price')}}" min="0" max="10000000" class="form-control">
    </div>
    <div class="form-group col-md-2">
        <label class="control-label" for="qty">{{ __('generic.quantity') }}</label>
        <input type="number" name="qty" value="{{old('qty') ?? 1}}" min="1" max="1000" class="form-control">
    </div>

    <div class="form-group col-md-12">
        <label class="control-label" for="notice">{{ __('generic.notice') }}</label>
        <textarea name="notice" class="form-control">{{old('notice')}}</textarea>
    </div>
    <input type="hidden" name="order_id" value="{{$order_id}}">
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary save">{{ __('voyager::generic.add') }}</button>
    </div>
</form>

@section('javascript')
    <script>
        $(document).ready(function () {
            $('select.select2-ajax-item').each(function() {
                $(this).select2({
                    width: '100%',
                    ajax: {
                        url: $(this).data('get-items-route'),
                        data: function (params) {
                            var query = {
                                search: params.term,
                            };
                            return query;
                        }
                    }
                });

                $(this).on('select2:select',function(e){
                    var data = e.params.data;
                    if (data.id == '') {
                        // "None" was selected. Clear all selected options
                        $(this).val([]).trigger('change');
                    } else {
                        $(e.currentTarget).find("option[value='" + data.id + "']").attr('selected','selected');
                        $('input[name=price]').val(data.price);
                    }
                });

                $(this).on('select2:unselect',function(e){
                    var data = e.params.data;
                    $(e.currentTarget).find("option[value='" + data.id + "']").attr('selected',false);
                });
            });
        });
    </script>
@stop

resources/views/admin/items/form-edit.blade.php
<form role="form"
      class="form-edit-add"
      action="{{route('admin.items.update_ajax')}}"
      method="POST">
    @method('PUT')
    {{ csrf_field() }}

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="form-group col-md-7">
        <label class="control-label" for="service_id">{{ __('generic.service') }}</label>
        <select class="form-control select2-ajax-item"
                name="service_id"
                data-get-items-route="{{route('admin.services.list')}}">
            <option value="">{{__('voyager::generic.none')}}</option>
            @inject('service_model', 'App\Service')
            @php $services = $service_model->all() @endphp
            @foreach($services as $service)
                <option value="{{ $service->id }}" {{$model->service->id === $service->id ? 'selected' : ''}}>
                    {{ $service->name }}  ({{ $service->price }} ₸)
                </option>
            @endforeach
        </select>
    </div>
    <div class="form-group col-md-3">
        <label class="control-label" for="price">{{ __('generic.price') }} (₸)</label>
        <input type="number" name="price" value="{{$model->price}}" min="0" max="10000000" class="form-control">
    </div>
    <div class="form-group col-md-2">
        <label class="control-label" for="qty">{{ __('generic.quantity') }}</label>
        <input type="number" name="qty" value="{{$model->qty}}" min="1" max="1000" class="form-control">
    </div>

    <div class="form-group col-md-12">
        <label class="control-label" for="notice">{{ __('generic.notice') }}</label>
        <textarea name="notice" class="form-control">{{$model->notice}}</textarea>
    </div>
    <input type="hidden" name="item_id" value="{{$model->id}}">
    <div class="panel-footer">
        <button type="submit" class="btn btn-primary save">{{ __('voyager::generic.save') }}</button>
    </div>
</form>

@section('javascript')
    <script>
        $(document).ready(function () {
            $('select.select2-ajax-item').each(function() {
                $(this).select2({
                    width: '100%',
                    ajax: {
                        url: $(this).data('get-items-route'),
                        data: function (params) {
                            var query = {
                                search: params.term,
                            };
                            return query;
                        }
                    }
                });

                $(this).on('select2:select',function(e){
                    var data = e.params.data;
                    if (data.id == '') {
                        // "None" was selected. Clear all selected options
                        $(this).val([]).trigger('change');
                    } else {
                        $(e.currentTarget).find("option[value='" + data.id + "']").attr('selected','selected');
                        $('input[name=price]').val(data.price);
                    }
                });

                $(this).on('select2:unselect',function(e){
                    var data = e.params.data;
                    $(e.currentTarget).find("option[value='" + data.id + "']").attr('selected',false);
                });
            });
        });
    </script>
@stop

resources/views/admin/items/table.blade.php
@php
    $exist_items = (App\Order::with('items')->find($order_id))->items;
@endphp

@if (count($exist_items) > 0)
    <h4 class="title-form-h4">{{__('generic.order_services')}}</h4>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">{{__('voyager::generic.name')}}</th>
            <th scope="col">{{__('generic.notice')}}</th>
            <th scope="col">{{__('generic.quantity')}}</th>
            <th scope="col">{{__('generic.total_price')}}</th>
            <th scope="col" class="text-right">{{__('voyager::generic.actions')}}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($exist_items as $k => $exist_item)
            <tr>
                <th scope="row">{{$k+1}}</th>
                <td>
                    {{$exist_item->service->name}} ({{$exist_item->service->price}} ₸) <br>
                    {!! $exist_item->price ? '<small class="text-info">'.__('generic.custom_price'). ': '.$exist_item->price.' ₸</small>' : ''!!}
                </td>
                <td>{{$exist_item->notice}}</td>
                <td>{{$exist_item->qty}}</td>
                <td>{{$exist_item->qty * ($exist_item->price ?? $exist_item->service->price)}} ₸</td>
                <td>
                    <span class="pull-right">
                        @include('partials.button-modal-delete', ['model' => $exist_item, 'route_name' => 'admin.items.delete'])
                    </span>
                    <span class="pull-right">
                        @include('partials.button-modal-edit-item', ['model' => $exist_item])
                    </span>
                    {{--<a href="{{ route('admin.car_user.edit', $exist_item->pivot->id) }}"--}}
                       {{--class="btn btn-sm btn-primary pull-right desctable" style="display:inline;">--}}
                        {{--<i class="voyager-edit"></i> {{ __('voyager::generic.edit') }}--}}
                    {{--</a>--}}
                    {{--<a href="{{ route('admin.car_user.show', $exist_item->pivot->id) }}"--}}
                       {{--class="btn btn-sm btn-warning pull-right desctable" style="display:inline; margin-right:5px;">--}}
                        {{--<i class="voyager-eye"></i> {{ __('voyager::generic.view') }}--}}
                    {{--</a>--}}
                </td>
            </tr>
        @endforeach
        <tr>
            <td colspan="6" class="text-right">
                <strong>{{__('generic.total')}}: </strong>
                <span class="font-weight-bold">{{App\Facades\Order::getTotalPrice($order_id)}}</span>
            </td>
        </tr>
        </tbody>
    </table>
@endif