routes/web.php
<?php

use App\Facades\Osmicard;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NexmoSMSController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('auth', 'verified');

Auth::routes(['verify' => true]);

Route::middleware('auth')->group(function () {
    Route::group(['prefix' => 'admin'], function () {

        Voyager::routes();

        Route::group(['middleware' => ['admin.user']], function () {

            Route::group(['prefix' => 'users', 'as' => 'admin.users.'], function () {
                Route::post('store_ajax',    ['as' => 'store_ajax',  'uses' => 'UserController@storeAjax']);
//            Route::delete('delete_car/{id}',    ['as' => 'delete_car',  'uses' => 'UserController@delete_car']);
                Route::post('select2',     ['as' => 'select2',        'uses' => 'UserController@select2']);
            });

            Route::group(['prefix' => 'agents', 'as' => 'admin.agents.'], function () {
                Route::post('approve_ajax',    ['as' => 'approve_ajax',  'uses' => 'AgentController@approveAjax']);
            });

            Route::group(['prefix' => 'dropzone', 'as' => 'admin.dropzone.'], function () {
                Route::get('/',        ['as' => 'index', 'uses' => 'PhotoController@index']);
                Route::post('store',   ['as' => 'store', 'uses' => 'PhotoController@store']);
            });

            Route::group(['prefix' => 'photos', 'as' => 'admin.photos.'], function () {
                Route::get('delete/{id}',        ['as' => 'delete', 'uses' => 'PhotoController@destroy']);
            });

            Route::group(['prefix' => 'orders', 'as' => 'admin.orders.'], function () {
                Route::post('photos',     ['as' => 'store_photos',  'uses' => 'OrderController@storePhotos']);
                Route::post('status',     ['as' => 'status',        'uses' => 'OrderController@updateStatus']);
            });

            Route::group(['prefix' => 'items', 'as' => 'admin.items.'], function () {
                Route::post('store',            ['as' => 'store',   'uses' => 'ItemController@store']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'ItemController@destroy']);
                Route::put('update_ajax',        ['as' => 'update_ajax',  'uses' => 'ItemController@updateAjax']);
//            Route::post('create_card',      ['as' => 'create_card',  'uses' => 'ItemController@createCard']);
            });

            Route::group(['prefix' => 'agent_orders', 'as' => 'admin.agent_orders.'], function () {
                Route::post('store',            ['as' => 'store',   'uses' => 'AgentOrderController@store']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'AgentOrderController@destroy']);
            });

            Route::group(['prefix' => 'card_templates', 'as' => 'admin.card_templates.'], function () {
                Route::get('fields',       ['as' => 'fields',   'uses' => 'CardTemplateController@fields']);
            });

            Route::group(['prefix' => 'cards', 'as' => 'admin.cards.'], function () {
                Route::post('store_ajax',       ['as' => 'store_ajax',   'uses' => 'CardController@storeAjax']);
                Route::post('update_event_ajax', ['as' => 'update_event_ajax',   'uses' => 'CardController@updateEventAjax']);
                Route::post('qrcode_ajax', ['as' => 'qrcode_ajax',   'uses' => 'CardController@getQRCodeAjax']);
                Route::post('send_sms_ajax', ['as' => 'send_sms_ajax',   'uses' => 'CardController@sendSMSAjax']);
            });

            Route::group(['prefix' => 'fields', 'as' => 'admin.fields.'], function () {
                Route::post('store_ajax',       ['as' => 'store_ajax',   'uses' => 'FieldController@storeAjax']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'FieldController@destroy']);
            });

            Route::group(['prefix' => 'services', 'as' => 'admin.services.'], function () {
                Route::get('services/list', ['as' => 'list', 'uses' => 'ServiceController@list']);
            });

            Route::group(['prefix' => 'verify', 'as' => 'admin.verify.'], function () {
                Route::post('send/{phone}', ['as' => 'send', 'uses' => 'VerifyController@send']);
                Route::post('check/{code}', ['as' => 'check', 'uses' => 'VerifyController@check']);
            });

            Route::get('sendSMS', [NexmoSMSController::class, 'index']);

            Route::group(['prefix' => 'report', 'as' => 'admin.report.'], function () {
                Route::get('/',    ['as' => 'index',  'uses' => 'ReportController@index']);
                Route::get('/search',    ['as' => 'search',  'uses' => 'ReportController@search']);
            });
        });

    });
});


// Agents
Route::middleware(['auth'])->group(function () {
    Route::group(['prefix' => 'agent', 'as' => 'agent.'], function () {
        Route::group(['prefix' => 'cards', 'as' => 'cards.'], function () {
            Route::get('/', ['as' => 'index', 'uses' => 'AgentCardController@index']);
            Route::get('show', ['as' => 'show', 'uses' => 'AgentCardController@show']);
            Route::post('store_ajax', ['as' => 'store_ajax',   'uses' => 'AgentCardController@storeAjax']);
            Route::post('update_event_ajax', ['as' => 'update_event_ajax',   'uses' => 'AgentCardController@updateEventAjax']);
            Route::post('get_card_ajax', ['as' => 'get_card_ajax',   'uses' => 'AgentCardController@getCardAjax']);
            Route::post('send_sms_ajax', ['as' => 'send_sms_ajax',   'uses' => 'AgentCardController@sendSMSAjax']);
            Route::post('qrcode_ajax', ['as' => 'qrcode_ajax',   'uses' => 'AgentCardController@getQRCodeAjax']);
        });
        Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
            Route::post('store', ['as' => 'store',   'uses' => 'AgentOrderController@store']);
        });
        Route::get('dashboard', ['as' => 'dashboard',  'uses' => 'AgentDashboardController@index']);
    });
});

// Voyager
//Route::group(['as' => 'voyager.'], function () {
//    event(new TCG\Voyager\Events\Routing());
//
//    Route::get('login', ['uses' => 'Voyager\VoyagerAuthController@login', 'as' => 'login']);
//
//    event(new TCG\Voyager\Events\RoutingAfter());
//});

// Some test
//Route::get('phpinfo', function () {
//    phpinfo();
//});

resources/views/partials/button-modal-delete.blade.php
<a href="javascript:;" title="{{ __('voyager::generic.delete') }}" class="btn btn-danger delete" data-id="{{ $model->id }}" id="delete-{{ $model->id }}" >
    <i class="voyager-trash"></i> <span class="hidden-xs hidden-sm">{{ __('voyager::generic.delete') }}</span>
</a>

<div class="modal modal-danger fade" tabindex="-1" id="delete_modal_{{$model->id}}" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="{{ __('voyager::generic.close') }}"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="voyager-trash"></i>
                    {{ __('voyager::generic.delete_question') }}
                </h4>
            </div>
            <div class="modal-footer">
                <form action="{{ route($route_name, $model->id) }}" id="delete_form_{{$model->id}}" method="POST">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <input type="submit" class="btn btn-danger pull-right delete-confirm"
                           value="{{ __('voyager::generic.delete_confirm') }}">
                </form>
                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">{{ __('voyager::generic.cancel') }}</button>
            </div>
        </div>
    </div>
</div>

@push('javascript')
    <script>
        $(document).ready(function () {
            $('#delete-{{$model->id}}').on('click', function (e) {
                $('#delete_modal_{{$model->id}}').modal('show');
            });
        });
    </script>
@endpush

resources/views/partials/button-modal-edit-item.blade.php
<a href="javascript:;" title="{{ __('voyager::generic.edit') }}" class="btn btn-warning edit" data-id="{{ $model->id }}" id="edit-{{ $model->id }}" >
    <i class="voyager-edit"></i> <span class="hidden-xs hidden-sm">{{ __('voyager::generic.edit') }}</span>
</a>

<div class="modal modal-warning fade" tabindex="-1" id="edit_modal_{{$model->id}}" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="{{ __('voyager::generic.close') }}"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="voyager-edit"></i>
                    {{ __('voyager::generic.edit') }}
                </h4>
            </div>
            <div class="modal-footer">
                @include('admin.items.form-edit', ['item' => $model])
            </div>
        </div>
    </div>
</div>

@push('javascript')
    <script>
        $(document).ready(function () {
            $('#edit-{{$model->id}}').on('click', function (e) {
                $('#edit_modal_{{$model->id}}').modal('show');
            });
        });
    </script>
@endpush

resources/views/partials/modal-add-card.blade.php
<div class="modal modal-success fade" tabindex="-1" id="addNewCardModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="{{ __('voyager::generic.close') }}"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="voyager-certificate"></i>
                    {{ __('generic.add_new_card') }}
                </h4>
            </div>
            <div class="modal-body">

                <div class="form-edit-add" role="form" >
                    <div class="row">
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="panel-body">
                            <form action="" id="formAddNewCardAjax">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="full_name">{{ __('generic.full_name') }}</label>
                                    <input type="text" class="form-control" id="full_name" name="full_name" placeholder=""
                                           value="{{ old('full_name') }}" required>
                                </div>

                                @inject('user', App\User)
                                @php
                                    $masters = $user::master()->get();
                                @endphp
                                <div class="form-group">
                                    <label for="master">{{ __('generic.master') }}</label>
                                    <select name="master" class="form-control" required>
                                        <option value=""></option>
                                        @foreach($masters as $master)
                                        <option value="{{$master->name}}">{{$master->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="car_number">{{ __('generic.car_vin_and_number') }}</label>
                                    <input type="text" class="form-control" id="car_number" name="car_number" placeholder=""
                                           value="{{ old('car_number') }}" required>
                                </div>

                                <div class="form-group">
                                    <label for="roll_number">{{ __('generic.roll_number') }} / {{ __('generic.batch_number') }}</label>
                                    <input type="text" class="form-control" id="roll_number" name="roll_number" placeholder=""
                                           value="{{ old('roll_number') }}" required>
                                </div>

                                <input type="hidden" name="item_id" value="">

                                <div class="alert alert-success" style="display: none"></div>
                                <div class="alert-system"></div>
                                <button type="submit" class="btn btn-primary pull-right save" id="submitFormAddNewCardAjax">
                                    <span class="spiner"></span>
                                    {{ __('voyager::generic.add') }}
                                </button>
                            </form>
                        </div>


                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

@push('javascript')
    <script>
        $(document).ready(function () {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            // Define variables
            var form = $('#formAddNewCardAjax');
            var fullNameField = form.find('input[name=full_name]');
            var masterField = form.find('select[name=master]');
            var carNumberField = form.find('input[name=car_number]');
            var rollNumberField = form.find('input[name=roll_number]');
            var itemIdField = form.find('input[name=item_id]');

            // Event Listeners for buttons
            var buttonsModal = document.querySelectorAll('.btn-add-new-card');
            if (buttonsModal.length > 0) {
                buttonsModal.forEach(function (el) {
                    el.addEventListener('click', function(e) {
                        e.preventDefault();
                        $('#addNewCardModal').modal('show');
                        itemIdField.val('');
                        itemIdField.val($(this).data('item'));
                    });
                })
            }

            // On submit form
            form.on('submit', function(e){
                e.preventDefault();

                var this_this = $(this);
                var sumbit_button = $(this).find('button[type="submit"]');

                var fullName = fullNameField.val();
                var master = masterField.val();
                var carNumber = carNumberField.val();
                var rollNumber = rollNumberField.val();
                var itemId = itemIdField.val();

                data = {
                    full_name: fullName,
                    master: master,
                    car_number: carNumber,
                    roll_number: rollNumber,
                    item_id: itemId,
                };

                $.ajax({
                    type:'POST',
                    url: '{{route('admin.cards.store_ajax')}}',
                    data: data,
                    beforeSend: function( xhr ) {
                        sumbit_button.addClass('loading');
                    },
                    success: function(data) {
                        sumbit_button.removeClass('loading');
                        sumbit_button.hide();
                        console.log(data);
                        if (data.success ?? data.card) {
                            console.log(data);
                            console.log(data.success);

                            this_this.find('.alert').addClass('alert-success').html((data.success && data.card) ? 'Карта <strong>' + data.card + '</strong> успешно создана.' : '').show();
                            this_this.find('.alert-system').html('<string>Подождите, идет перезагрузка страницы ...</string>').show();
                            setTimeout(function () {
                                document.location.reload();
                            }, 2000)

                        }
                        if (data.error) {
                            console.log(data.error);
                            this_this.find('.alert').addClass('alert-danger').text(data.error).show();
                            setTimeout(function () {
                                this_this.find('.alert-danger').removeClass('alert-danger').hide().text('');
                                $('#addNewCardModal').modal('hide');
                            }, 2000);
                        }
                    }
                });
            });

        });

    </script>
@endpush

resources/views/partials/modal-add-user.blade.php
<div class="modal modal-success fade" tabindex="-1" id="addNewUserModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="{{ __('voyager::generic.close') }}"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="voyager-user"></i>
                    {{ __('generic.add_new_user') }}
                </h4>
            </div>
            <div class="modal-body">

                <div class="form-edit-add" id="formAddNewUserAjax" role="form" >
                    {{ csrf_field() }}

                    <div class="row">

                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="panel-body">
                            <div class="form-group">
                                <label for="name">{{ __('voyager::generic.name') }}</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="{{ __('voyager::generic.name') }}"
                                       value="{{ old('name') }}">
                            </div>

                            <div class="form-group">
                                <label for="email">{{ __('voyager::generic.email') }}</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="{{ __('voyager::generic.email') }}"
                                       value="{{ old('email') }}">
                            </div>

                            <div class="form-group">
                                <label for="phone">{{ __('voyager::generic.phone') }}</label>
                                <input type="tel" class="form-control" id="phone" name="phone" placeholder="+77XXXXXXX"
                                       value="{{ old('phone') }}">
                                <span class="validation-input-msg"></span>
                            </div>
                            <div class="form-group">
                                @include('partials.toggle-verify-phone', ['phone_input_id' => 'phone'])
                            </div>


                            <button class="btn btn-primary pull-right save" id="submitFormAddNewUserAjax">
                                {{ __('voyager::generic.add') }}
                            </button>
                        </div>

                        <div class="alert alert-success" style="display: none"></div>
                    </div>



                </div>
            </div>

        </div>
    </div>
</div>

@push('javascript')
    <script>
        $(document).ready(function () {

            // Functions
            function validatePhone(strNumber) {
                var phone = {{config('services.nexmo.phone_number_pattern')}};
                if((strNumber.match(phone))) {
                    return true;
                } else {
                    return false;
                }
            }
            // End Functions

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            {{--var phoneInputSourceForm = $('#{{$phone_input_id}}');--}}
            var rootDivForm = $('#formAddNewUserAjax');
            var nameField = rootDivForm.find('input[name=name]');
            var phoneField = rootDivForm.find('input[name=phone]');
            var emailField = rootDivForm.find('input[name=email]');

            var validationPhoneField = phoneField.next('.validation-input-msg');

            $('#btnAddNewUserModal').on('click', function (e) {
                $('#addNewUserModal').modal('show');
            });

            $('#verifyToggle').click(function () {
               $('#verifyToggleSection').toggleClass('active');
            });

            $("input#phone").on('keyup', function (e) {
                validationPhoneField.text('').removeClass('success error');
                if (validatePhone($(this).val())) {
                    validationPhoneField.text('Верный формат').addClass('success');
                } else {
                    validationPhoneField.text('Не валидный номмер, попробуйте формат +77XXXXXXX').addClass('error');
                }
            });

            $("#submitFormAddNewUserAjax").on('click', function(e){

                e.preventDefault();

                var nameUser = nameField.val();
                var emailUser = emailField.val();
                var phoneNumber = phoneField.val();

                validationPhoneField.text('').removeClass('success error');

                if (validatePhone(phoneNumber)) {
                    validationPhoneField.text('Верный формат').addClass('success');
                    data = {
                        name: nameUser, phone: phoneNumber
                    };
                    if (emailUser) {
                        data.email = emailUser;
                    }
                    $.ajax({
                        type:'POST',
                        url: '{{route('admin.users.store_ajax')}}',
                        data: data,
                        success: function(data) {
                            console.log(data);
                            if (data.success) {
                                console.log(data.success);
                                rootDivForm.find('.alert').addClass('alert-success').text(data.success ? 'Пользователь добавлен успешно':'').show();
                                setTimeout(function () {
                                    rootDivForm.find('.alert-success').removeClass('alert-success').hide().text('');
                                }, 3000);
                            }
                            if (data.error) {
                                console.log(data.error);
                                rootDivForm.find('.alert').addClass('alert-danger').text(data.error).show();
                                setTimeout(function () {
                                    rootDivForm.find('.alert-danger').removeClass('alert-danger').hide().text('');
                                }, 3000);
                            }
                        }
                    });

                } else {
                    validationPhoneField.text('Не валидный номмер, попробуйте формат +77XXXXXXX').addClass('error');
                }
            });

        });

    </script>
@endpush

resources/views/partials/modal-verify-phone.blade.php
<div class="modal modal-success fade" tabindex="-1" id="verifyPhoneNumberModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="{{ __('voyager::generic.close') }}"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="voyager-telephone"></i>
                    {{ __('generic.phone_number_verification') }}
                </h4>
            </div>
            <div class="modal-body">
                @include('partials.form-verify-phone')
            </div>
        </div>
    </div>
</div>

@push('javascript')
    <script>
        $(document).ready(function () {
            $('#btnVerifyPhoneNumberModal').on('click', function (e) {
                $('#verifyPhoneNumberModal').modal('show');
            });
        });
    </script>
@endpush

resources/views/partials/modal-warranty-event.blade.php
<div class="modal modal-info fade" tabindex="-1" id="registerWarrantyEvent" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="{{ __('voyager::generic.close') }}"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="voyager-certificate"></i>
                    {{ __('generic.register_warranty_event') }} <br>
                    {{ __('generic.warranty_card') }}: <strong class="header-number"></strong>
                </h4>
            </div>
            <div class="modal-body">

                <div class="form-edit-add" role="form" >
                    <div class="row">
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="panel-body">
                            <form action="">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="warranty_event">{{ __('generic.warranty_event') }}</label>
                                    <textarea type="text" class="form-control" id="warranty_event" name="warranty_event" required>{{ old('warranty_event') }}</textarea>
                                </div>

                                <input type="hidden" name="number" value="">

                                <div class="alert alert-success" style="display: none"></div>
                                <div class="alert-system text-info" style="display: none"></div>

                                <button type="submit" class="btn btn-primary pull-right save" id="submitFormAddNewCardAjax">
                                    <span class="spiner"></span>
                                    {{ __('voyager::generic.add') }}
                                </button>
                            </form>
                        </div>


                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

@push('javascript')
    <script>
        $(document).ready(function () {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            // Define variables
            var modal = document.getElementById('registerWarrantyEvent');
            var form = modal.querySelector('form');
            var warrantyEventField = form.querySelector('textarea[name=warranty_event]');
            var numberField = form.querySelector('input[name=number]');
            var headerNumber = modal.querySelector('.header-number');

            // Event Listeners for buttons
            var buttonsModal = document.querySelectorAll('.btn-register-warranty-event');
            if (buttonsModal.length > 0) {
                buttonsModal.forEach(function (el) {
                    el.addEventListener('click', function(e) {
                        e.preventDefault();
                        $(modal).modal('show');
                        numberField.value = '';
                        numberField.value = $(this).data('number');
                        headerNumber.innerText = '';
                        headerNumber.innerText = $(this).data('number');

                    });
                })
            }

            // On submit form
            $(form).on('submit', function(e){
                e.preventDefault();

                var this_this = $(this);
                var sumbit_button = $(this).find('button[type="submit"]');

                var warrantyEvent = warrantyEventField.value;
                var number = numberField.value;

                data = {
                    warranty_event: warrantyEvent,
                    number: number,
                };

                $.ajax({
                    type:'POST',
                    url: '{{route('admin.cards.update_event_ajax')}}',
                    data: data,
                    beforeSend: function( xhr ) {
                        sumbit_button.addClass('loading');
                    },
                    success: function(data) {
                        sumbit_button.removeClass('loading');
                        console.log(data);
                        if (data.success ?? data.events) {
                            console.log(data.success);
                            sumbit_button.hide();
                            this_this.find('.alert').addClass('alert-success').html((data.success && data.events) ? '<h5>Регистрация гарантии успешно добавлена</h5> <strong>' + data.events + '</strong>' : '').show();
                            this_this.find('.alert-system').html('<string>Подождите, идет перезагрузка страницы ...</string>').show();
                            setTimeout(function () {
                                document.location.reload();
                            }, 2000);

                        }
                        if (data.error) {
                            console.log(data.error);
                            this_this.find('.alert').addClass('alert-danger').text(data.error).show();
                            setTimeout(function () {
                                this_this.find('.alert-danger').removeClass('alert-danger').hide().text('');
                                $('#addNewCardModal').modal('hide');
                            }, 2000);
                        }
                    }
                });
            });

        });

    </script>
@endpush