routes/web.php
<?php

use App\Facades\Osmicard;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NexmoSMSController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('auth', 'verified');

Auth::routes(['verify' => true]);

Route::middleware('auth')->group(function () {
    Route::group(['prefix' => 'admin'], function () {

        Voyager::routes();

        Route::group(['middleware' => ['admin.user']], function () {

            Route::group(['prefix' => 'users', 'as' => 'admin.users.'], function () {
                Route::post('store_ajax',    ['as' => 'store_ajax',  'uses' => 'UserController@storeAjax']);
//            Route::delete('delete_car/{id}',    ['as' => 'delete_car',  'uses' => 'UserController@delete_car']);
                Route::post('select2',     ['as' => 'select2',        'uses' => 'UserController@select2']);
            });

            Route::group(['prefix' => 'agents', 'as' => 'admin.agents.'], function () {
                Route::post('approve_ajax',    ['as' => 'approve_ajax',  'uses' => 'AgentController@approveAjax']);
            });

            Route::group(['prefix' => 'dropzone', 'as' => 'admin.dropzone.'], function () {
                Route::get('/',        ['as' => 'index', 'uses' => 'PhotoController@index']);
                Route::post('store',   ['as' => 'store', 'uses' => 'PhotoController@store']);
            });

            Route::group(['prefix' => 'photos', 'as' => 'admin.photos.'], function () {
                Route::get('delete/{id}',        ['as' => 'delete', 'uses' => 'PhotoController@destroy']);
            });

            Route::group(['prefix' => 'orders', 'as' => 'admin.orders.'], function () {
                Route::post('photos',     ['as' => 'store_photos',  'uses' => 'OrderController@storePhotos']);
                Route::post('status',     ['as' => 'status',        'uses' => 'OrderController@updateStatus']);
            });

            Route::group(['prefix' => 'items', 'as' => 'admin.items.'], function () {
                Route::post('store',            ['as' => 'store',   'uses' => 'ItemController@store']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'ItemController@destroy']);
                Route::put('update_ajax',        ['as' => 'update_ajax',  'uses' => 'ItemController@updateAjax']);
//            Route::post('create_card',      ['as' => 'create_card',  'uses' => 'ItemController@createCard']);
            });

            Route::group(['prefix' => 'agent_orders', 'as' => 'admin.agent_orders.'], function () {
                Route::post('store',            ['as' => 'store',   'uses' => 'AgentOrderController@store']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'AgentOrderController@destroy']);
            });

            Route::group(['prefix' => 'card_templates', 'as' => 'admin.card_templates.'], function () {
                Route::get('fields',       ['as' => 'fields',   'uses' => 'CardTemplateController@fields']);
            });

            Route::group(['prefix' => 'cards', 'as' => 'admin.cards.'], function () {
                Route::post('store_ajax',       ['as' => 'store_ajax',   'uses' => 'CardController@storeAjax']);
                Route::post('update_event_ajax', ['as' => 'update_event_ajax',   'uses' => 'CardController@updateEventAjax']);
                Route::post('qrcode_ajax', ['as' => 'qrcode_ajax',   'uses' => 'CardController@getQRCodeAjax']);
                Route::post('send_sms_ajax', ['as' => 'send_sms_ajax',   'uses' => 'CardController@sendSMSAjax']);
            });

            Route::group(['prefix' => 'fields', 'as' => 'admin.fields.'], function () {
                Route::post('store_ajax',       ['as' => 'store_ajax',   'uses' => 'FieldController@storeAjax']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'FieldController@destroy']);
            });

            Route::group(['prefix' => 'services', 'as' => 'admin.services.'], function () {
                Route::get('services/list', ['as' => 'list', 'uses' => 'ServiceController@list']);
            });

            Route::group(['prefix' => 'verify', 'as' => 'admin.verify.'], function () {
                Route::post('send/{phone}', ['as' => 'send', 'uses' => 'VerifyController@send']);
                Route::post('check/{code}', ['as' => 'check', 'uses' => 'VerifyController@check']);
            });

            Route::get('sendSMS', [NexmoSMSController::class, 'index']);

            Route::group(['prefix' => 'report', 'as' => 'admin.report.'], function () {
                Route::get('/',    ['as' => 'index',  'uses' => 'ReportController@index']);
                Route::get('/search',    ['as' => 'search',  'uses' => 'ReportController@search']);
            });
        });

    });
});


// Agents
Route::middleware(['auth'])->group(function () {
    Route::group(['prefix' => 'agent', 'as' => 'agent.'], function () {
        Route::group(['prefix' => 'cards', 'as' => 'cards.'], function () {
            Route::get('/', ['as' => 'index', 'uses' => 'AgentCardController@index']);
            Route::get('show', ['as' => 'show', 'uses' => 'AgentCardController@show']);
            Route::post('store_ajax', ['as' => 'store_ajax',   'uses' => 'AgentCardController@storeAjax']);
            Route::post('update_event_ajax', ['as' => 'update_event_ajax',   'uses' => 'AgentCardController@updateEventAjax']);
            Route::post('get_card_ajax', ['as' => 'get_card_ajax',   'uses' => 'AgentCardController@getCardAjax']);
            Route::post('send_sms_ajax', ['as' => 'send_sms_ajax',   'uses' => 'AgentCardController@sendSMSAjax']);
            Route::post('qrcode_ajax', ['as' => 'qrcode_ajax',   'uses' => 'AgentCardController@getQRCodeAjax']);
        });
        Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
            Route::post('store', ['as' => 'store',   'uses' => 'AgentOrderController@store']);
        });
        Route::get('dashboard', ['as' => 'dashboard',  'uses' => 'AgentDashboardController@index']);
    });
});

// Voyager
//Route::group(['as' => 'voyager.'], function () {
//    event(new TCG\Voyager\Events\Routing());
//
//    Route::get('login', ['uses' => 'Voyager\VoyagerAuthController@login', 'as' => 'login']);
//
//    event(new TCG\Voyager\Events\RoutingAfter());
//});

// Some test
//Route::get('phpinfo', function () {
//    phpinfo();
//});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.css' rel='stylesheet'>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ route('agent.dashboard') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @auth
                    <ul class="navbar-nav nav-agent-main mr-auto ml-md-3">
                        <li class="nav-item mr-md-3">
                            <a href="{{route('agent.dashboard')}}" class="nav-link {{(request()->is('agent/dashboard')) ? 'active' : '' }}">Отгрузки</a>
                        </li>
                        <li class="nav-item mr-md-3">
                            <a href="{{route('agent.cards.index')}}" class="nav-link {{(request()->is('agent/cards')) ? 'active' : '' }}">Все карты</a>
                        </li>
                    </ul>
                    @endauth
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script>
        (function() {

        })();
    </script>
    @yield('javascript')
    @stack('javascript')
</body>
</html>