routes/web.php
<?php

use App\Facades\Osmicard;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NexmoSMSController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware('auth', 'verified');

Auth::routes(['verify' => true]);

Route::middleware('auth')->group(function () {
    Route::group(['prefix' => 'admin'], function () {

        Voyager::routes();

        Route::group(['middleware' => ['admin.user']], function () {

            Route::group(['prefix' => 'users', 'as' => 'admin.users.'], function () {
                Route::post('store_ajax',    ['as' => 'store_ajax',  'uses' => 'UserController@storeAjax']);
//            Route::delete('delete_car/{id}',    ['as' => 'delete_car',  'uses' => 'UserController@delete_car']);
                Route::post('select2',     ['as' => 'select2',        'uses' => 'UserController@select2']);
            });

            Route::group(['prefix' => 'agents', 'as' => 'admin.agents.'], function () {
                Route::post('approve_ajax',    ['as' => 'approve_ajax',  'uses' => 'AgentController@approveAjax']);
            });

            Route::group(['prefix' => 'dropzone', 'as' => 'admin.dropzone.'], function () {
                Route::get('/',        ['as' => 'index', 'uses' => 'PhotoController@index']);
                Route::post('store',   ['as' => 'store', 'uses' => 'PhotoController@store']);
            });

            Route::group(['prefix' => 'photos', 'as' => 'admin.photos.'], function () {
                Route::get('delete/{id}',        ['as' => 'delete', 'uses' => 'PhotoController@destroy']);
            });

            Route::group(['prefix' => 'orders', 'as' => 'admin.orders.'], function () {
                Route::post('photos',     ['as' => 'store_photos',  'uses' => 'OrderController@storePhotos']);
                Route::post('status',     ['as' => 'status',        'uses' => 'OrderController@updateStatus']);
            });

            Route::group(['prefix' => 'items', 'as' => 'admin.items.'], function () {
                Route::post('store',            ['as' => 'store',   'uses' => 'ItemController@store']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'ItemController@destroy']);
                Route::put('update_ajax',        ['as' => 'update_ajax',  'uses' => 'ItemController@updateAjax']);
//            Route::post('create_card',      ['as' => 'create_card',  'uses' => 'ItemController@createCard']);
            });

            Route::group(['prefix' => 'agent_orders', 'as' => 'admin.agent_orders.'], function () {
                Route::post('store',            ['as' => 'store',   'uses' => 'AgentOrderController@store']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'AgentOrderController@destroy']);
            });

            Route::group(['prefix' => 'card_templates', 'as' => 'admin.card_templates.'], function () {
                Route::get('fields',       ['as' => 'fields',   'uses' => 'CardTemplateController@fields']);
            });

            Route::group(['prefix' => 'cards', 'as' => 'admin.cards.'], function () {
                Route::post('store_ajax',       ['as' => 'store_ajax',   'uses' => 'CardController@storeAjax']);
                Route::post('update_event_ajax', ['as' => 'update_event_ajax',   'uses' => 'CardController@updateEventAjax']);
                Route::post('qrcode_ajax', ['as' => 'qrcode_ajax',   'uses' => 'CardController@getQRCodeAjax']);
                Route::post('send_sms_ajax', ['as' => 'send_sms_ajax',   'uses' => 'CardController@sendSMSAjax']);
            });

            Route::group(['prefix' => 'fields', 'as' => 'admin.fields.'], function () {
                Route::post('store_ajax',       ['as' => 'store_ajax',   'uses' => 'FieldController@storeAjax']);
                Route::delete('delete/{id}',    ['as' => 'delete',  'uses' => 'FieldController@destroy']);
            });

            Route::group(['prefix' => 'services', 'as' => 'admin.services.'], function () {
                Route::get('services/list', ['as' => 'list', 'uses' => 'ServiceController@list']);
            });

            Route::group(['prefix' => 'verify', 'as' => 'admin.verify.'], function () {
                Route::post('send/{phone}', ['as' => 'send', 'uses' => 'VerifyController@send']);
                Route::post('check/{code}', ['as' => 'check', 'uses' => 'VerifyController@check']);
            });

            Route::get('sendSMS', [NexmoSMSController::class, 'index']);

            Route::group(['prefix' => 'report', 'as' => 'admin.report.'], function () {
                Route::get('/',    ['as' => 'index',  'uses' => 'ReportController@index']);
                Route::get('/search',    ['as' => 'search',  'uses' => 'ReportController@search']);
            });
        });

    });
});


// Agents
Route::middleware(['auth'])->group(function () {
    Route::group(['prefix' => 'agent', 'as' => 'agent.'], function () {
        Route::group(['prefix' => 'cards', 'as' => 'cards.'], function () {
            Route::get('/', ['as' => 'index', 'uses' => 'AgentCardController@index']);
            Route::get('show', ['as' => 'show', 'uses' => 'AgentCardController@show']);
            Route::post('store_ajax', ['as' => 'store_ajax',   'uses' => 'AgentCardController@storeAjax']);
            Route::post('update_event_ajax', ['as' => 'update_event_ajax',   'uses' => 'AgentCardController@updateEventAjax']);
            Route::post('get_card_ajax', ['as' => 'get_card_ajax',   'uses' => 'AgentCardController@getCardAjax']);
            Route::post('send_sms_ajax', ['as' => 'send_sms_ajax',   'uses' => 'AgentCardController@sendSMSAjax']);
            Route::post('qrcode_ajax', ['as' => 'qrcode_ajax',   'uses' => 'AgentCardController@getQRCodeAjax']);
        });
        Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
            Route::post('store', ['as' => 'store',   'uses' => 'AgentOrderController@store']);
        });
        Route::get('dashboard', ['as' => 'dashboard',  'uses' => 'AgentDashboardController@index']);
    });
});

// Voyager
//Route::group(['as' => 'voyager.'], function () {
//    event(new TCG\Voyager\Events\Routing());
//
//    Route::get('login', ['uses' => 'Voyager\VoyagerAuthController@login', 'as' => 'login']);
//
//    event(new TCG\Voyager\Events\RoutingAfter());
//});

// Some test
//Route::get('phpinfo', function () {
//    phpinfo();
//});

app/Agent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'contact', 'is_approved'
    ];

    /**
     * Return User.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    /**
     * Return Cards.
     */
    public function cards()
    {
        return $this->hasMany('App\AgentCard');
    }

    /**
     * Return Orders.
     */
    public function orders()
    {
        return $this->hasMany('App\AgentOrder');
    }
}

app/Card.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Card extends Model
{
    protected $fillable = ['number'];

    public function item()
    {
        return $this->belongsTo('App\Item');
    }
}

app/Http/Controllers/AgentController.php
<?php

namespace App\Http\Controllers;

use App\Agent;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class AgentController extends Controller
{
    /**
     * Update is_approved via AJAX.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function approveAjax(Request $request)
    {
        $rules = [
            'agent_id' => 'numeric',
            'is_approved' => 'boolean',
        ];
        $validator = Validator::make($request->all(), $rules);

        if ( $validator->fails() ) {
            $response = [
                'success' => false,
                'errors' => $validator->getMessageBag()->toArray()
            ];
        } else {
            $agent = Agent::find($request->agent_id);
            $agent->is_approved = $request->is_approved;
            $agent->save();

            $response = [
                'success' => true,
                'errors' => 'ok'
            ];

        }

        return response()->json($response);
    }
}

app/Http/Controllers/CardController.php
<?php

namespace App\Http\Controllers;

use App\Card;
use App\Events\CardCreated;
use App\Events\OrderCreated;
use App\Facades\Osmicard;
use App\Http\Requests\StoreCardRequest;
use App\Item;
use App\Notifications\CardCreatedNotification;
use App\Services\CardService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Validator;

class CardController extends Controller
{
    /**
     * Store card via AJAX.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeAjax(Request $request)
    {
        $rules = [
            'full_name' => 'required',
            'master' => 'required',
            'car_number' => 'required',
            'roll_number' => '',
            'item_id' => 'required',
        ];
        $validator = Validator::make($request->all(), $rules);

        if ( $validator->fails() ) {
            return response()->json([
                'success' => false,
                'errors' => $validator->getMessageBag()->toArray()
            ]);
        }

        $item = Item::find($request->item_id);
        $phone = $item->order->user->phone;
        $template = $item->service->cardTemplate;
        $number = substr($phone, 2);
        $description = $item->notice;
        $service = $item->service->name;
        if ($description) {
            $service_and_description = $service . PHP_EOL . '---- ОПИСАНИЕ ----' . PHP_EOL . $description;
        } else {
            $service_and_description = $service;
        }
        // Templates field cases
        $values = [];
        $values[] = [
            'label' => 'ДАТА УСТАНОВКИ',
            'value' => date('Y-m-d'),
        ];
        $values[] = [
            'label' => 'ВЛАДЕЛЕЦ',
            'value' => $request->full_name,
        ];
        $values[] = [
            'label' => 'МАСТЕР',
            'value' => $request->master,
        ];
        $values[] = [
            'label' => 'МАРКА',
            'value' => $item->order->car,
        ];
        $values[] = [
            'label' => 'ГОС.НОМЕР',
            'value' => $request->car_number,
        ];
        $values[] = [
            'label' => 'ПРОДУКТ',
            'value' => $service_and_description,
        ];
        $values[] = [
            'label' => 'НОМЕР ПАРТИИ',
            'value' => $request->roll_number,
        ];

        $args['values'] = $values;

        $created_card_number = '';
        foreach ( range('A', 'Z') as $letter ) {
            $prefix = env('OSMICARD_NUMBER_PREFIX', 'G');
            $response = Osmicard::createSingleOsmicard($prefix.$letter.$number, $template->name, $args);

            if ( empty($response['RCODE']) && !empty($response['general']['serialNo']) && $response['general']['serialNo'] === $prefix.$letter.$number) {
                $created_card_number = $response['general']['serialNo'];
                break;
            }
        }

        if ( $created_card_number ) {
            $card = Card::create([
                'number' => $created_card_number,
            ]);
            $item->card()->save($card);

//            event(new CardCreated($card));

            return response()->json(['success' => true, 'card' => $created_card_number], 200);
        }

        return response()->json(['error' => 'К сожалению карта не была создана'], 200);
    }

    /**
     * Update warranty event card via AJAX.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateEventAjax(Request $request)
    {
        $rules = [
            'warranty_event' => 'required',
            'number' => 'required',
        ];
        $validator = Validator::make($request->all(), $rules);

        if ( $validator->fails() ) {
            return response()->json([
                'success' => false,
                'errors' => $validator->getMessageBag()->toArray()
            ]);
        }

        $string = '<div>' . date('Y-m-d') . ': ' . $request->warranty_event . '</div>';
        $card = Osmicard::updateWarrantyEventSingleOsmicard($request->number, $string);

        if (!empty($card['general']['serialNo'])) {
            $new_event_val = Osmicard::getSingleOsmicardWarrantyEvent($card['general']['serialNo']);
            return response()->json(['success' => true, 'events' => $new_event_val], 200);
        } else {
            return response()->json([
                'success' => false,
                'errors' => 'Card was not updated'
            ]);
        }

    }

    /**
     * Get QR code via AJAX.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function getQRCodeAjax(Request $request)
    {
        $link = Osmicard::getLinkOsmicard($request->number, 'qr');

        if (!empty($link['link'])) {
            return response()->json([
                'success' => true,
                'link' => $link['link']], 200);
        } else {
            return response()->json([
                'success' => false,
                'errors' => 'Card was not found'
            ], 404);
        }
    }

    /**
     * Send SMS via AJAX.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function sendSMSAjax(Request $request)
    {
        $card = Card::findOrFail($request->card_id);
        $user = $card->item->order->user;
        $link = Osmicard::getLinkOsmicard($card->number);
        $success = false;

        if (!empty($link['link'])) {
            $msg = 'GMASK. Гарантийная карта: ' . $link['link'];
            Notification::send($user, new CardCreatedNotification($msg, $card->number));
            $success = true;
        }

        return response()->json([
            'success' => $success,
        ], 200);
    }
}

resources/views/agents/cards/table.blade.php
@if (count($cards) > 0)
    <div class="agent-cards-list">
        <div class="agent-cards-list__head">
            <div class="agent-cards-list__head--index">#</div>
            <div class="agent-cards-list__head--number">{{__('generic.number')}}</div>
        </div>
        <div class="agent-cards-list__body">
            @foreach($cards as $k => $card)
                <div class="agent-cards-list__body-row">
                    <div class="agent-cards-list__body-row-visible">
                        <div class="agent-cards-list__body-row-visible--index">
                            {{$k+1}}
                        </div>
                        <div class="agent-cards-list__body-row-visible--number">
                            {{$card->number}}
                        </div>
                        <div class="agent-cards-list__body-row-visible--action">
                            <button data-number="{{$card->number}}">
                                <i class="fa fa-angle-down"></i>
                            </button>
                        </div>
                    </div>
                    <div class="agent-cards-list__body-row-toggle">
                        <div class="agent-cards-list__body-row-toggle-in">
                            <span class="load"><i class="fas fa-circle-notch fa-spin"></i></span>
                            <ul class="agent-card-fields"></ul>
                            <div class="agent-card-nav">
                                <a href="#" data-number="{{$card->number}}"
                                   class="btn btn-sm btn-primary desctable btn-register-warranty-event">
                                    {{ __('generic.register_warranty_event') }}
                                </a>
                                <a href="#" data-number="{{$card->number}}" class="btn btn-secondary btn-show-qr-code">
                                    <img src="{{asset('storage')}}/qr.svg" alt="">
                                </a>
                                <a href="#" data-number="{{$card->number}}" class="btn btn-info btn-send-sms">
                                    <span class="spiner"></span>
                                    <img src="{{asset('storage')}}/sms.svg" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

            @endforeach
        </div>
        <div class="agent-cards-pagination">
            {{ $cards->links() }}
        </div>
    </div>
@else
    <div class="div alert alert-warning">{{ __('generic.you_have_not_warranty_cards') }}</div>
@endif
@include('agents/partials/modal-warranty-qr-code')
@push('javascript')
    <script>
        (function() {
            const toggleButtons = document.querySelectorAll('.agent-cards-list__body-row-visible--action button');

            if (!toggleButtons.length) return;

            toggleButtons.forEach( function(el) {
                el.addEventListener('click', function(e) {
                    e.preventDefault();
                    const row = e.target.closest('.agent-cards-list__body-row');
                    const toggle = row.querySelector('.agent-cards-list__body-row-toggle');
                    [...row.parentNode.children].forEach(function (el) {
                        el.classList.remove('toggled');
                        el.querySelector('.agent-cards-list__body-row-toggle').style.height = '';
                    });
                    if ( row.classList.contains('toggled') ) {
                        row.classList.remove('toggled');
                        toggle.style.height = '';
                    } else {
                        row.classList.add('toggled');
                        toggle.style.height = toggle.children[0].offsetHeight + 'px';
                        getDataAgentWarrantyCard(e.target);
                    }

                })
            })

            const getDataAgentWarrantyCard = function (el) {
                const number = el.dataset.number;
                const row = el.closest('.agent-cards-list__body-row');
                const rows = document.querySelectorAll('.agent-cards-list__body-row')
                const toggle = row.querySelector('.agent-cards-list__body-row-toggle')
                const load = row.querySelector('.load');
                const for_fields = row.querySelector('.agent-card-fields');
                if (!load) return;
                $.ajax({
                    type: 'POST',
                    url: '{{ route('agent.cards.get_card_ajax') }}',
                    data: { number: number },
                    beforeSend: function( xhr ) {
                        row.classList.add('loading');
                        rows.forEach(function (el) {
                            el.style.pointerEvents = 'none';
                        });
                    },
                    success: function(data) {
                        toggle.style.height = toggle.children[0].offsetHeight + 'px';
                        row.classList.remove('loading');
                        rows.forEach(function (el) {
                            el.style.pointerEvents = '';
                        });
                        if ( data.success ) {
                            let html = '';
                            for (const key in data.fields) {
                                html += `<li><span>${key}:</span><span></span><span>${data.fields[key]}</span></li>`;
                            }
                            console.log(load)
                            load.remove();
                            for_fields.innerHTML = html;
                            toggle.style.height = toggle.children[0].offsetHeight + 'px';
                        }
                        if ( data.error ) {
                            console.log(data.error);
                        }
                    }
                });
            }
        })();

        (function () {
            // Send warranty sms
            let smsButtons = document.querySelectorAll('.btn-send-sms');
            if (smsButtons.length > 0) {
                smsButtons.forEach(function (el) {
                    el.addEventListener('click', function (e) {
                        e.preventDefault();
                        var this_this = this;
                        if ( confirm("Вы подтверждаете отправку SMS") ) {
                            $.ajax({
                                type:'POST',
                                url: '{{ route('agent.cards.send_sms_ajax') }}',
                                data: { number: this.dataset.number },
                                beforeSend: function( xhr ) {
                                    this_this.classList.add('loading');
                                },
                                success: function(data) {
                                    this_this.classList.remove('loading');
                                    const alert = document.createElement('span');
                                    alert.innerHTML = data.msg;
                                    this_this.after(alert);
                                    if (data.success) {
                                        alert.classList.add('text-success');
                                    } else {
                                        alert.classList.add('text-danger');
                                    }
                                    setTimeout(function () {
                                        alert.remove();
                                    }, 5000);
                                }
                            });
                        }
                    });
                });
            }
        })();
    </script>
@endpush